apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kustomize:
    paths:
      - ./infra/k8s/overlays/dev
build:
  local:
    push: false
  artifacts:
    - image: ellenkramp/auth
      context: .
      docker:
        dockerfile: auth/Dockerfile
      sync:
        manual:
          - src: "auth/src/**/*.ts"
            dest: /app
    - image: ellenkramp/client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "/**/*.js"
            dest: .
    - image: ellenkramp/tickets
      context: .
      docker:
        dockerfile: tickets/Dockerfile
      sync:
        manual:
          - src: "tickets/src/**/*.ts"
            dest: /app
    - image: ellenkramp/orders
      context: .
      docker:
        dockerfile: orders/Dockerfile
      sync:
        manual:
          - src: "orders/src/**/*.ts"
            dest: /app
    - image: ellenkramp/expiration
      context: .
      docker:
        dockerfile: expiration/Dockerfile
      sync:
        manual:
          - src: "expiration/src/**/*.ts"
            dest: /app
    - image: ellenkramp/payments
      context: .
      docker:
        dockerfile: payments/Dockerfile
      sync:
        manual:
          - src: "payments/src/**/*.ts"
            dest: /app
